name: Deploy Backend to DigitalOcean
on:
  push:
    branches: [ main ]
    paths:
      - 'CineCompassBackend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CineCompassBackend

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./CineCompassBackend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cinecompass-backend:latest

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cinecompass-backend:latest
            docker stop backend-container || true
            docker rm backend-container || true
            docker run -d -p 8000:8000 --name backend-container ${{ secrets.DOCKERHUB_USERNAME }}/cinecompass-backend:latest